insert into trayecto (id_tren, id_estacion, nombre) values (31, 72, 'Alcanhões');
insert into trayecto (id_tren, id_estacion, nombre) values (28, 65, 'Itaberaí');
insert into trayecto (id_tren, id_estacion, nombre) values (82, 38, 'Fenghuo');
insert into trayecto (id_tren, id_estacion, nombre) values (61, 24, 'Lubenia');
insert into trayecto (id_tren, id_estacion, nombre) values (50, 26, 'Fredrikstad');
insert into trayecto (id_tren, id_estacion, nombre) values (76, 34, 'Lyasny');
insert into trayecto (id_tren, id_estacion, nombre) values (17, 103, 'Capacmarca');
insert into trayecto (id_tren, id_estacion, nombre) values (11, 13, 'Gapuk');
insert into trayecto (id_tren, id_estacion, nombre) values (54, 88, 'Purong');
insert into trayecto (id_tren, id_estacion, nombre) values (58, 19, 'Wakaseko');
insert into trayecto (id_tren, id_estacion, nombre) values (23, 67, 'Byczyna');
insert into trayecto (id_tren, id_estacion, nombre) values (78, 65, 'Lidköping');
insert into trayecto (id_tren, id_estacion, nombre) values (15, 12, 'Middleton');
insert into trayecto (id_tren, id_estacion, nombre) values (54, 29, 'Tampa');
insert into trayecto (id_tren, id_estacion, nombre) values (18, 74, 'Cottbus');
insert into trayecto (id_tren, id_estacion, nombre) values (38, 78, 'Dhankutā');
insert into trayecto (id_tren, id_estacion, nombre) values (87, 30, 'Arīḩā');
insert into trayecto (id_tren, id_estacion, nombre) values (67, 97, 'Banjar Tiga');
insert into trayecto (id_tren, id_estacion, nombre) values (53, 106, 'Drayton Valley');
insert into trayecto (id_tren, id_estacion, nombre) values (26, 94, 'Calçada');
insert into trayecto (id_tren, id_estacion, nombre) values (75, 14, 'Betim');
insert into trayecto (id_tren, id_estacion, nombre) values (82, 30, 'Mendeleyevsk');
insert into trayecto (id_tren, id_estacion, nombre) values (35, 39, 'Negla');
insert into trayecto (id_tren, id_estacion, nombre) values (80, 16, 'Maramag');
insert into trayecto (id_tren, id_estacion, nombre) values (18, 37, 'Fenhe');
insert into trayecto (id_tren, id_estacion, nombre) values (60, 92, 'Stepove');
insert into trayecto (id_tren, id_estacion, nombre) values (98, 103, 'Jialu');
insert into trayecto (id_tren, id_estacion, nombre) values (39, 19, 'Osinniki');
insert into trayecto (id_tren, id_estacion, nombre) values (50, 36, 'Tangzha');
insert into trayecto (id_tren, id_estacion, nombre) values (19, 70, 'Lagoa Seca');
insert into trayecto (id_tren, id_estacion, nombre) values (16, 12, 'Ibadan');
insert into trayecto (id_tren, id_estacion, nombre) values (78, 30, 'Paris 13');
insert into trayecto (id_tren, id_estacion, nombre) values (45, 86, 'Xinfeng');
insert into trayecto (id_tren, id_estacion, nombre) values (79, 78, 'Bjästa');
insert into trayecto (id_tren, id_estacion, nombre) values (90, 10, 'Rovensko pod Troskami');
insert into trayecto (id_tren, id_estacion, nombre) values (94, 50, 'Angra dos Reis');
insert into trayecto (id_tren, id_estacion, nombre) values (59, 15, 'Taoyuan');
insert into trayecto (id_tren, id_estacion, nombre) values (45, 42, 'Cabeças Verdes');
insert into trayecto (id_tren, id_estacion, nombre) values (22, 24, 'Sibulan');
insert into trayecto (id_tren, id_estacion, nombre) values (53, 17, 'Sātkhira');
insert into trayecto (id_tren, id_estacion, nombre) values (71, 7, 'Totness');
insert into trayecto (id_tren, id_estacion, nombre) values (32, 93, 'Itapecerica');
insert into trayecto (id_tren, id_estacion, nombre) values (105, 50, 'Mizur');
insert into trayecto (id_tren, id_estacion, nombre) values (82, 98, 'Daliang');
insert into trayecto (id_tren, id_estacion, nombre) values (87, 46, 'Pizarro');
insert into trayecto (id_tren, id_estacion, nombre) values (88, 60, 'Arras');
insert into trayecto (id_tren, id_estacion, nombre) values (79, 67, 'Gambang');
insert into trayecto (id_tren, id_estacion, nombre) values (35, 16, 'Lac-Brome');
insert into trayecto (id_tren, id_estacion, nombre) values (37, 50, 'Sishan');
insert into trayecto (id_tren, id_estacion, nombre) values (68, 54, 'Jinghong');
insert into trayecto (id_tren, id_estacion, nombre) values (63, 71, 'Melaka');
insert into trayecto (id_tren, id_estacion, nombre) values (26, 19, 'Gibato');
insert into trayecto (id_tren, id_estacion, nombre) values (33, 69, 'Lipu');
insert into trayecto (id_tren, id_estacion, nombre) values (68, 42, 'Dunleer');
insert into trayecto (id_tren, id_estacion, nombre) values (36, 89, 'Shuishi');
insert into trayecto (id_tren, id_estacion, nombre) values (35, 37, 'Pruszcz');
insert into trayecto (id_tren, id_estacion, nombre) values (103, 48, 'Daveluyville');
insert into trayecto (id_tren, id_estacion, nombre) values (21, 92, 'Pokój');
insert into trayecto (id_tren, id_estacion, nombre) values (104, 37, 'Berlin');
insert into trayecto (id_tren, id_estacion, nombre) values (89, 62, 'Pyt-Yakh');
insert into trayecto (id_tren, id_estacion, nombre) values (78, 51, 'Sapphaya');
insert into trayecto (id_tren, id_estacion, nombre) values (99, 18, 'Cipanas');
insert into trayecto (id_tren, id_estacion, nombre) values (66, 66, 'Hetou');
insert into trayecto (id_tren, id_estacion, nombre) values (50, 29, 'Mpumalanga');
insert into trayecto (id_tren, id_estacion, nombre) values (62, 83, 'Panikihan');
insert into trayecto (id_tren, id_estacion, nombre) values (10, 101, 'Tafí Viejo');
insert into trayecto (id_tren, id_estacion, nombre) values (69, 73, 'Gumdag');
insert into trayecto (id_tren, id_estacion, nombre) values (27, 83, 'Krasnoye');
insert into trayecto (id_tren, id_estacion, nombre) values (62, 50, 'Qianjin');
insert into trayecto (id_tren, id_estacion, nombre) values (44, 48, 'Podosinovets');
insert into trayecto (id_tren, id_estacion, nombre) values (105, 37, 'Lipin Bor');
insert into trayecto (id_tren, id_estacion, nombre) values (55, 93, 'Pelaya');
insert into trayecto (id_tren, id_estacion, nombre) values (60, 72, 'Dongdu');
insert into trayecto (id_tren, id_estacion, nombre) values (79, 36, 'Penisihan');
insert into trayecto (id_tren, id_estacion, nombre) values (69, 37, 'San Felipe');
insert into trayecto (id_tren, id_estacion, nombre) values (73, 29, 'Pinglumiao');
insert into trayecto (id_tren, id_estacion, nombre) values (22, 101, 'Shangmachang');
insert into trayecto (id_tren, id_estacion, nombre) values (37, 44, 'Gus’-Zheleznyy');
insert into trayecto (id_tren, id_estacion, nombre) values (56, 87, 'Wangunsari');
insert into trayecto (id_tren, id_estacion, nombre) values (64, 90, 'Tawangsari');
insert into trayecto (id_tren, id_estacion, nombre) values (58, 36, 'Yuanling');
insert into trayecto (id_tren, id_estacion, nombre) values (23, 88, 'Bogotá');
insert into trayecto (id_tren, id_estacion, nombre) values (29, 58, 'Deauville');
insert into trayecto (id_tren, id_estacion, nombre) values (37, 77, 'Wakduwa’ Barat');
insert into trayecto (id_tren, id_estacion, nombre) values (81, 69, 'Sietesz');
insert into trayecto (id_tren, id_estacion, nombre) values (28, 50, 'Vladimir');
insert into trayecto (id_tren, id_estacion, nombre) values (78, 85, 'Casa Quemada');
insert into trayecto (id_tren, id_estacion, nombre) values (12, 64, 'Dawa-Dawa');
insert into trayecto (id_tren, id_estacion, nombre) values (63, 92, 'Emmen');
insert into trayecto (id_tren, id_estacion, nombre) values (92, 61, 'Taraban Timur');
insert into trayecto (id_tren, id_estacion, nombre) values (41, 45, 'Jinping');
insert into trayecto (id_tren, id_estacion, nombre) values (67, 50, 'Rizal');
insert into trayecto (id_tren, id_estacion, nombre) values (90, 18, 'Herrera');
insert into trayecto (id_tren, id_estacion, nombre) values (61, 23, 'El Monte');
insert into trayecto (id_tren, id_estacion, nombre) values (43, 58, 'Watergrasshill');
insert into trayecto (id_tren, id_estacion, nombre) values (20, 49, 'Ede');
insert into trayecto (id_tren, id_estacion, nombre) values (71, 101, 'Leicheng');
insert into trayecto (id_tren, id_estacion, nombre) values (78, 20, 'Benoni');
insert into trayecto (id_tren, id_estacion, nombre) values (26, 87, 'Sedlčany');
insert into trayecto (id_tren, id_estacion, nombre) values (47, 93, 'Gongju');
