insert into tren (modelo, capacidad) values ('Charger', 1);
insert into tren (modelo, capacidad) values ('GTI', 2);
insert into tren (modelo, capacidad) values ('Viper', 3);
insert into tren (modelo, capacidad) values ('LR3', 4);
insert into tren (modelo, capacidad) values ('B-Series', 5);
insert into tren (modelo, capacidad) values ('Sportage', 6);
insert into tren (modelo, capacidad) values ('Silverado 1500', 7);
insert into tren (modelo, capacidad) values ('F250', 8);
insert into tren (modelo, capacidad) values ('Trans Sport', 9);
insert into tren (modelo, capacidad) values ('Malibu Maxx', 10);
insert into tren (modelo, capacidad) values ('Grand Marquis', 11);
insert into tren (modelo, capacidad) values ('Silhouette', 12);
insert into tren (modelo, capacidad) values ('Corsica', 13);
insert into tren (modelo, capacidad) values ('Legacy', 14);
insert into tren (modelo, capacidad) values ('5000S', 15);
insert into tren (modelo, capacidad) values ('Intrigue', 16);
insert into tren (modelo, capacidad) values ('SVX', 17);
insert into tren (modelo, capacidad) values ('RX-8', 18);
insert into tren (modelo, capacidad) values ('Defender', 19);
insert into tren (modelo, capacidad) values ('928', 20);
insert into tren (modelo, capacidad) values ('Taurus', 21);
insert into tren (modelo, capacidad) values ('S4', 22);
insert into tren (modelo, capacidad) values ('MKT', 23);
insert into tren (modelo, capacidad) values ('SVX', 24);
insert into tren (modelo, capacidad) values ('Eclipse', 25);
insert into tren (modelo, capacidad) values ('GS', 26);
insert into tren (modelo, capacidad) values ('Lanos', 27);
insert into tren (modelo, capacidad) values ('Camry Hybrid', 28);
insert into tren (modelo, capacidad) values ('S4', 29);
insert into tren (modelo, capacidad) values ('Dakota', 30);
insert into tren (modelo, capacidad) values ('Passat', 31);
insert into tren (modelo, capacidad) values ('Savana 2500', 32);
insert into tren (modelo, capacidad) values ('S-Series', 33);
insert into tren (modelo, capacidad) values ('Diablo', 34);
insert into tren (modelo, capacidad) values ('924 S', 35);
insert into tren (modelo, capacidad) values ('Mustang', 36);
insert into tren (modelo, capacidad) values ('Acadia', 37);
insert into tren (modelo, capacidad) values ('S80', 38);
insert into tren (modelo, capacidad) values ('Savana 1500', 39);
insert into tren (modelo, capacidad) values ('Cobalt', 40);
insert into tren (modelo, capacidad) values ('62', 41);
insert into tren (modelo, capacidad) values ('Tempo', 42);
insert into tren (modelo, capacidad) values ('STS-V', 43);
insert into tren (modelo, capacidad) values ('Suburban 2500', 44);
insert into tren (modelo, capacidad) values ('Montero Sport', 45);
insert into tren (modelo, capacidad) values ('Versa', 46);
insert into tren (modelo, capacidad) values ('A8', 47);
insert into tren (modelo, capacidad) values ('RL', 48);
insert into tren (modelo, capacidad) values ('Accord', 49);
insert into tren (modelo, capacidad) values ('FR-S', 50);
insert into tren (modelo, capacidad) values ('B-Series', 51);
insert into tren (modelo, capacidad) values ('Town Car', 52);
insert into tren (modelo, capacidad) values ('Firefly', 53);
insert into tren (modelo, capacidad) values ('Tribeca', 54);
insert into tren (modelo, capacidad) values ('Town Car', 55);
insert into tren (modelo, capacidad) values ('G-Series G10', 56);
insert into tren (modelo, capacidad) values ('SL65 AMG', 57);
insert into tren (modelo, capacidad) values ('Trooper', 58);
insert into tren (modelo, capacidad) values ('CR-V', 59);
insert into tren (modelo, capacidad) values ('Truck', 60);
insert into tren (modelo, capacidad) values ('Silverado', 61);
insert into tren (modelo, capacidad) values ('Dakota', 62);
insert into tren (modelo, capacidad) values ('Spider', 63);
insert into tren (modelo, capacidad) values ('Scoupe', 64);
insert into tren (modelo, capacidad) values ('Type 2', 65);
insert into tren (modelo, capacidad) values ('2500', 66);
insert into tren (modelo, capacidad) values ('S90', 67);
insert into tren (modelo, capacidad) values ('745', 68);
insert into tren (modelo, capacidad) values ('GTO', 69);
insert into tren (modelo, capacidad) values ('Reno', 70);
insert into tren (modelo, capacidad) values ('Cutlass Supreme', 71);
insert into tren (modelo, capacidad) values ('Odyssey', 72);
insert into tren (modelo, capacidad) values ('A8', 73);
insert into tren (modelo, capacidad) values ('Legend', 74);
insert into tren (modelo, capacidad) values ('DBS', 75);
insert into tren (modelo, capacidad) values ('E-Series', 76);
insert into tren (modelo, capacidad) values ('Lancer', 77);
insert into tren (modelo, capacidad) values ('Sienna', 78);
insert into tren (modelo, capacidad) values ('Eurovan', 79);
insert into tren (modelo, capacidad) values ('Terrain', 80);
insert into tren (modelo, capacidad) values ('Fit', 81);
insert into tren (modelo, capacidad) values ('Sonoma Club Coupe', 82);
insert into tren (modelo, capacidad) values ('Thunderbird', 83);
insert into tren (modelo, capacidad) values ('200', 84);
insert into tren (modelo, capacidad) values ('Discovery', 85);
insert into tren (modelo, capacidad) values ('Escalade ESV', 86);
insert into tren (modelo, capacidad) values ('Monte Carlo', 87);
insert into tren (modelo, capacidad) values ('Coupe Quattro', 88);
insert into tren (modelo, capacidad) values ('Monza', 89);
insert into tren (modelo, capacidad) values ('Explorer', 90);
insert into tren (modelo, capacidad) values ('Tacoma', 91);
insert into tren (modelo, capacidad) values ('Charger', 92);
insert into tren (modelo, capacidad) values ('Ram', 93);
insert into tren (modelo, capacidad) values ('3 Series', 94);
insert into tren (modelo, capacidad) values ('Tacoma Xtra', 95);
insert into tren (modelo, capacidad) values ('Continental GT', 96);
insert into tren (modelo, capacidad) values ('LS', 97);
insert into tren (modelo, capacidad) values ('Forester', 98);
insert into tren (modelo, capacidad) values ('Equator', 99);
insert into tren (modelo, capacidad) values ('MX-6', 100);
